/**
 * Types that mirror lac-data.json — generated by `lac export --data`
 */

export interface LacViewUser {
  userGuide?: string
  knownLimitations?: string[]
  problem?: string
  successCriteria?: string
  tags?: string[]
}

export interface LacDecision {
  date: string
  decision: string
  rationale?: string
  choice?: string
}

export interface LacCodeSnippet {
  label: string
  code: string
  language?: string
}

export interface LacPublicEntry {
  name: string
  type: string
  description?: string
}

export interface LacViewDev {
  componentFile?: string
  implementation?: string
  implementationNotes?: string
  codeSnippets?: LacCodeSnippet[]
  decisions?: LacDecision[]
  externalDependencies?: string[]
  testStrategy?: string
  npmPackages?: string[]
  publicInterface?: LacPublicEntry[]
}

export interface LacViewProduct {
  problem?: string
  successCriteria?: string
  acceptanceCriteria?: string[]
  decisions?: LacDecision[]
  pmSummary?: string
  knownLimitations?: string[]
  releaseVersion?: string
}

export interface LacViewSupport {
  knownLimitations?: string[]
  annotations?: string[]
  problem?: string
}

export type LacStatus = 'draft' | 'active' | 'frozen' | 'deprecated'
export type LacView = 'user' | 'dev' | 'product' | 'support'

export interface LacFeatureEntry {
  featureKey: string
  title: string
  status: LacStatus
  domain: string
  tags: string[]
  priority?: number
  externalDependencies: string[]
  views: {
    user?: LacViewUser
    dev?: LacViewDev
    product?: LacViewProduct
    support?: LacViewSupport
  } & Record<string, Record<string, unknown> | undefined>
}

export interface LacMeta {
  projectName: string
  generatedAt: string
  lacVersion: string
  featureCount: number
  domains: string[]
  definedViews: string[]
}

export interface LacDataExport {
  meta: LacMeta
  features: LacFeatureEntry[]
}
